### ISSUE TITLE
Section equivalent for arrays?

### ISSUE THREAD

**Issue by guybedford** [LongTengDao/j-toml#15]
Is it possible to have something like `Section` for arrays?

Example scenario:

Code:

```js
import TOML from '@ltd/j-toml';

const parsed = TOML.parse('version = 0.1');
parsed.task = parsed.task || [];
parsed.task.push({ custom: 'task' });

console.log(TOML.stringify(parsed, { newline: '\n' }));
```

Currently this outputs:

```
version = 0.1
task = [
	{ custom = 'task' },
]
```

when I would like it to output:

```
version = 0.1
[[task]]
custom = 'task'
```

If I wrap the array creation with `Section` it throws. If I try use `multiline` it throws as well. Is there an option here for the `parsed.task = []` initialization line?

**Comment by LongTengDao** [comment]
Welcome @guybedford ,

the helper function `Section` is used for toml table only:

https://github.com/LongTengDao/j-toml/blob/432e39432db50f12cebbdfaa8c6fc865a74b5694/docs/English/README.md#L322

And the helper function `multiline` can not be used on toml array, because array is multiline (which means **static array** with newline after each array item) by default:

https://github.com/LongTengDao/j-toml/blob/432e39432db50f12cebbdfaa8c6fc865a74b5694/docs/English/README.md#L369

Currently, there are only one official way to mark an array as "array of tables":

https://github.com/LongTengDao/j-toml/blob/432e39432db50f12cebbdfaa8c6fc865a74b5694/docs/English/README.md#L368

Which means:

```js
parsed.task.push(TOML.Section({ custom: 'task' }));
```

If you really need an option to do this for the iniitialization line, in current vertion, hope this would help:

```js
parsed.task ??= new Proxy([], {
    set (target, key, value, proxy) {
        if ( typeof key==='symbol' || !/^(?:0|[1-9]\d*)$/.test(key) ) { return Reflect.set(target, key, value, proxy); }
        target[key] = TOML.Section(value);
        return true;
    }
});
```

---

It's not impossible to add an helper function which can directly mark an array as "array of tables", I didn't design it just because I consider that an "array of tables" can not be empty, and its items must all be section tables, so I thought it's more scrupulously to judge the array mode by its items' marks.

Welcome to feedback, if there are still some use cases not handy which I didn't considered, after you use the helpers above correctly under my explanation here.

**Comment by LongTengDao** [comment]
BTW: if you want better tree-shake, you may write `import * as TOML from '@ltd/j-toml'` rather than `import TOML from '@ltd/j-toml'`.

**Comment by guybedford** [comment]
@LongTengDao thanks for the feedback here - yes sorry I completely missed its the dictionary array element which forms the section here. I guess TOML isn't necessarily intuitive to understand. One thing that might help is checking that the defaults of this library line up with eg Rust's TOML implementation. The configurability is great, but having good defaults is everything too.

This project is great though, there isn't much else available for JS TOML, thanks for your work!

**Comment by LongTengDao** [comment]
> **Key words**: configurability vs good default (intuitive / Rust implementation)

Thank you for your suggestion, I will find chance to try them.
